L = 0.00585                 # metres, equals 1/2 of cell thickness
deltaT = 5                  # degrees C, magnitude of step change
start_time = 1207           # start time elapsed, when the heat flux jumps, seconds
start_time_addition = 10    # added to start time, determined manually, from the time diff when power is applied until temperature reaches steady state)
end_time = 1500             # end time elapsed to fit equation, seconds
heat_flux_offset = 276      # shift to heat flux curve so that steady state equals zero
fitting_time_skip = 20      # seconds, integer, ignore first few seconds because of overshoot