L = 0.005815                  # metres, equals 1/2 of cell thickness
deltaT = 5                  # degrees C, magnitude of step change
start_time = 6273           # start time elapsed, when the heat flux jumps, seconds
start_time_addition = 10    # added to start time, determined manually, from the time diff when power is applied until temperature reaches steady state)
end_time = 6773             # end time elapsed to fit equation, seconds
fitting_time_skip = 24      # seconds, integer, ignore first few seconds because of overshoot